"use strict";
exports.__esModule = true;
exports.userRoutes = void 0;
var express_1 = require("express");
var userControllers_1 = require("../controllers/userControllers");
var authHeader_1 = require("../middlewares/authHeader");
exports.userRoutes = (0, express_1.Router)();
exports.userRoutes.post("/users", userControllers_1.createUser);
exports.userRoutes.get("/users", authHeader_1.authenticateToken, userControllers_1.getAllUsers);
//userRoutes.put("/users/:id", updateUser);
exports.userRoutes.put("/users/changePassword/:username", userControllers_1.updatePassword);
exports.userRoutes["delete"]("/users/:username", authHeader_1.authenticateToken, userControllers_1.deleteUser);
exports.userRoutes.get("/users/:id", authHeader_1.authenticateToken, userControllers_1.getUser);
exports.userRoutes.post("/login", userControllers_1.Login);
